!function(){const ICONS={area:'<svg viewBox="0 0 24 24"><rect x="5" y="5" width="14" height="14" rx="2"/><path d="M9 5v14M15 5v14M5 9h14M5 15h14"/></svg>',perimeter:'<svg viewBox="0 0 24 24"><path d="M5 7h14"/><path d="M5 17h14"/><path d="M7 5v14"/><path d="M17 5v14"/><path d="M4 12h16"/><path d="M7 10l-3 2 3 2"/><path d="M17 10l3 2-3 2"/></svg>',corners:'<svg viewBox="0 0 24 24"><path d="M7 5v12h12"/><circle cx="7" cy="17" r="2"/><circle cx="19" cy="17" r="2"/><circle cx="7" cy="5" r="2"/></svg>',rooms:'<svg viewBox="0 0 24 24"><rect x="5" y="5" width="14" height="14" rx="2"/><path d="M12 5v14"/><path d="M5 12h14"/><path d="M9 9h.01M15 15h.01"/></svg>'};function setMetricIcon(valueId,iconKey){const v=(id=valueId,document.getElementById(id));var id;if(!v)return;const card=v.closest(".rpc-metric,.rp-metric,.stat-card");if(!card)return;let icon=card.querySelector(".rpc-metric-icon,.rp-metric-icon,.stat-icon");icon||(icon=document.createElement("div"),icon.className=card.classList.contains("rp-metric")?"rp-metric-icon":"rpc-metric-icon",card.insertBefore(icon,card.firstChild));icon.__rmIconKey!==iconKey&&(icon.__rmIconKey=iconKey,icon.innerHTML=ICONS[iconKey]||ICONS.area)}function applyMetricIcons(){setMetricIcon("rpcArea","area"),setMetricIcon("rpcPer","perimeter"),setMetricIcon("rpcLights","corners"),setMetricIcon("rpcRoomName","rooms"),setMetricIcon("rpArea","area"),setMetricIcon("rpPer","perimeter"),setMetricIcon("rpLights","corners"),setMetricIcon("rpElems","rooms")}const oldRpc=window.rpcUpdate;if("function"==typeof oldRpc&&!oldRpc.__metricIcons3628){window.rpcUpdate=function(){const r=oldRpc.apply(this,arguments);return setTimeout(applyMetricIcons,20),r},window.rpcUpdate.__metricIcons3628=!0;try{rpcUpdate=window.rpcUpdate}catch(__diagE913){window.__diagSilent&&window.__diagSilent(__diagE913)}}const oldRp=window.rpUpdateHome;if("function"==typeof oldRp&&!oldRp.__metricIcons3628){window.rpUpdateHome=function(){const r=oldRp.apply(this,arguments);return setTimeout(applyMetricIcons,20),r},window.rpUpdateHome.__metricIcons3628=!0;try{rpUpdateHome=window.rpUpdateHome}catch(__diagE913){window.__diagSilent&&window.__diagSilent(__diagE913)}}rmOnReady(applyMetricIcons),setTimeout(applyMetricIcons,80),setTimeout(applyMetricIcons,500);
(function(){
  var timer=0;
  function queue(){clearTimeout(timer);timer=setTimeout(applyMetricIcons,40);}
  rmOnReady(function(){
    var root=document.getElementById("rpCockpit")||document.body;
    if(!root||typeof MutationObserver==="undefined")return;
    new MutationObserver(queue).observe(root,{childList:true,subtree:true});
  });
})()}()